[options]
db_host = localhost
db_port = 5432
db_user = odoo18
db_password = 123
addons_path = /Users/virajkothari/Documents/odoo18/odoo/addons,/Users/virajkothari/Documents/Enterprise/v_18/enterprise,/Users/virajkothari/Documents/Project/my_pre_appstore
debug_mode = True
log_level = info
xmlrpc_port = 8000
gevent_port = 8072
smtp_server = smtp.example.com
smtp_port = 25
smtp_ssl = False
smtp_user = user@example.com
admin_passwd = $pbkdf2-sha512$600000$0zpnDKHU2jtnDCHEWAvBmA$y6PbXvnnGt6oLxTzzgmPItEie0j1qPuPbLTfACP3H/csKvGuDHeFYj3Vm1a.8sOmoP6hY8bnV0igjk/N0H2Z/g
